### ISSUE TITLE
Pedido de ajuda?!

### ISSUE THREAD

**Issue by bruno5198** [bruno5198/Trabalho2-Grupo2#1]
Boa tarde malta,

Quando corro um exercício que use a câmera do meu PC, como por exemplo o exercício 2 da aula 6, aparece-me o seguinte aviso/erro no terminal: "[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (935) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1"

O programa corre sem problma, no entanto não percebo o porquê de devolver esta mensagem de erro.
ALgum de vocês tem o mesmo problema e sabe o que se passa?

**Comment by PedroRibeiro37** [comment]
Boas,
nao faço ideia,
Pesquisei agora na net e ha bue malta com o mesmo erro.
https://github.com/TheImagingSource/tiscamera/issues/332
https://github.com/opencv/opencv/pull/14834

Tem aí bue malta a falar do erro, pode ser que alguma cena que eles dizem ajude

**Comment by Malhocas** [comment]
Boas, também tenho esse erro e na altura tentei pesquisar um bocado mas não encontrei assim nada rápido, acho que eram umas definições a ver com o GStreamer, mas como funciona na mesma, acabei por ignorar.

**Comment by bruno5198** [comment]
Ok, obrigado malta.
