### ISSUE TITLE
Funcionamento da deteção e cor "color_segmenter.py"!

### ISSUE THREAD

**Issue by bruno5198** [bruno5198/Trabalho2-Grupo2#10]
Boas,

@PedroRibeiro37
Dá-me ideia que a deteção de cor (HSV) não está a funcionar como deve se der. Podes verificar?

**Comment by PedroRibeiro37** [comment]
Boas, estive a verificar e de facto deve estar a haver um bug qualquer.
Quando fui alterar no ficheiro json usei estes parametros:H 0-103 S 0-256 V-220 a 256. Foi os que pareceram mais corretos na mascara para detetar a cor vermelha. a cena é que quando executo o programa deteta bem mas depois começa a deixar de detetar a cor, ou fica meio telemovel ou depois acaba por ficar so numa lateral do telemovel nao entendo.já estive a ver o codigo e tecnicamente se o rgb funciona bem o este tambem deveria funcionar, n entendo o pk...

**Comment by bruno5198** [comment]
Já viste se entra dentro do if da linha 105? Pode estar a acontecer que nem entra dentro desse if por algum motivo...

**Comment by PedroRibeiro37** [comment]
Boas,
estive a ver e o erro nao esta no color segmenter mas sim no ar_paint a ler o ficheiro.
Acho que ja consegui corrigir...
