### ISSUE TITLE
Problema com a tela branca

### ISSUE THREAD

**Issue by PedroRibeiro37** [bruno5198/Trabalho2-Grupo2#3]
Malta estou a ter problemas com a tela branca.
Quando tento por as imagens detetadas pela camera dá me erro.
Alguem me consegue ajudar ?

**Comment by bruno5198** [comment]
Boas,

Acho que vais ter de ser mais específico (ou eventualmente mostrar umas imagens para perceber qual está a ser mesmo o erro)...

**Comment by PedroRibeiro37** [comment]
Para ver se eu entendi, basicamente o que o stor quer é que inves de ter a tela branca  a desenhar,  ele quer a imagem da camera a aparecer na tela branca ao mesmo tempo que desenhas ?

**Comment by bruno5198** [comment]
Sim, penso que é isso.
