### ISSUE TITLE
Novos avanços!

### ISSUE THREAD

**Issue by bruno5198** [bruno5198/Trabalho2-Grupo2#4]
Boas malta,

Acabei de fazer o commit de uma nova versão do trabalho, já com a divisão entre trabalhos (color_segmenter.py & ar_paint.py) e com o acréscimo de algumas funcionalidades, em particular no ar_paint.py.

Qualquer coisa que não concordem ou qualquer erro que encontrem, digam...

Em relação à funcionalidade avançada 4, já fiz algumas coisas, mas ainda não acabei....não está fácil....

**Comment by PedroRibeiro37** [comment]
Malta,
uma coisa é suposto adicionarmos um novo modo de jogo para cada funcionalidade avançada ? ou é suposto ficar tudo junto?

**Comment by bruno5198** [comment]
@PedroRibeiro37  Estás a perguntar se cada funcionalidade avançada tem um argumento específico no argparse, é? Se for isso creio que a resposta é "nim"....pode ser assim ou pode fixar tudo junto e utilizar diferentes teclas para lançar as diferentes funcionalidades...

**Comment by PedroRibeiro37** [comment]
sim exato, como la diz substituir a tela branca pela imagem da camera, penso que peça um novo argumento no argparse digo eu nao ?

**Comment by bruno5198** [comment]
Sim, por mim parece-me bem. Crias, por exemplo, um argumento boleano no argparse que por default esteja a True e tenha a imagem da câmara (ou a imagem branca) e caso o utilizador queira mudar, define o argumento como False...

**Comment by PedroRibeiro37** [comment]
Boas malta, estive a ver e fiz tipo na camera a desenhar e a  aparecer ao mesmo tempo que quando desenhas no papel. n sei se fica mal ou n mas como o stor em termos de argumentos no argparse so tem para ir buscar um o ficheiro json fiz assim

**Comment by bruno5198** [comment]
Boas malta,

Acabei de adicionar ao "ar_paint.py" a funcionalidade avaçada 4 e 5. Ainda não está 100% pronta, mas diria que já está 90%...
