### ISSUE TITLE
Funcionalidade avançada 4

### ISSUE THREAD

**Issue by bruno5198** [bruno5198/Trabalho2-Grupo2#5]
Boa tarde malta,

Estou de volta da funcionalidade avançada 4, no entanto tenho alguns problemas...

Eu já consigo obter o contorno de cada uma das regiões de uma imagem e numerar as diferentes regiões (de forma aleatória e com números de 1 a 4), sendo que para a localização do número em questão utilizo o centroid da região onde quero escreve-lo. O problema é que, tendo a imagem abaixo como exemplo, a localização do centroid da região pintada a vermelho e da região pintada a azul é praticamente a mesma, o que faz com que a numeração de ambas as regiões fique dentro da região azul (sendo que devia ficar um número dentro da região azul e outro dentro da região vermelha). Alguma dica para resolver este problema?
![rabbit2](https://user-images.githubusercontent.com/58600049/142026940-4a2e24d9-b1b5-4b15-800b-1120a41a41e5.png)

**Comment by PedroRibeiro37** [comment]
ou seja pelo que entendi, neste caso tu consegues fazer com que o programa detete as duas formas mas o teu problema é que o numero que atribuis a cada forma se encontra localizado no centroide, isto é ficam numeros diferentes mas um em cima do outro que neste caso coincide com a imagem azul certo?

**Comment by bruno5198** [comment]
É isso mesmo. Neste caso ficam os dois números em cima um do outro e ambos em cima da região azul, o que está errado porque um número diz de facto respeito à região azul, mas o outro diz respeito à região vermelha...
E....a resposta obvia à minha questão/problema talvez seja "não uses o centroid". A questão é....então uso o quê?

**Comment by PedroRibeiro37** [comment]
eu posso estar a ser meio nabo mas não da para criar uma condição em que caso os dois centroides sejam muito proximos exiges que os numeros apareção separados por uma distancia do centroide ? esta me a entender ?

**Comment by PedroRibeiro37** [comment]
uma coisa mas essa imagem tambem não é um bocado complexa ?
se for tipo a do stor da aula acaba por ser mais facil ou n ?

**Comment by bruno5198** [comment]
Mas e que distância seria essa?
Sim, com a imagem do stor não acontece isto...

**Comment by PedroRibeiro37** [comment]
e se tipo, tu tens as coordenadas de todos os pontos do teu contorno certo ? e se escolheres para esses casos meter o numero em qualquer lugar desses pontos ?
assim ja n vai coincidir com a tua imagem azul

**Comment by bruno5198** [comment]
Não é uma solução que me agrade muito, mas de facto deve funcionar. Obrigado

**Comment by PedroRibeiro37** [comment]
Tipo eu estive a pensar e imagina deixas estar como estava a meter os numeros nos centroides e crias uma condiçao que caso o centroide da figura esteja fora da figura que tu queres pintar fazes entao uma randomizaçao para meter em qualquer ponto do teu desenho que pintaste... n sei se me expliquei bem mas acho q da para entender

**Comment by bruno5198** [comment]
Pensei exatamente no mesmo à pouco...E já consegui saber se o centroid está ou não dentro da figura, ainda não sei é como faço para obter umas coordenadas random só dentro do contorno...

**Comment by bruno5198** [comment]
Já consegui resolver o problema. Obrigado pela ajuda.
