### ISSUE TITLE
Estado atual do trabalho.

### ISSUE THREAD

**Issue by bruno5198** [bruno5198/Trabalho2-Grupo2#7]
Boa tarde malta,

@Rubenvale31 Tinhas ficado de fazer a Funcionalidade avançada 1, certo? Como está isso?º

@PedroRibeiro37  Já acabas-te a parte da Funcionalidade avançada 2, certo? Penso que seria fixe ficares encarregue de testar tudo o que já foi feito até ao mais pequeno pormenor, para despistar eventuais erros que possam existir...

@Malhocas Penso que ainda não pegas-te nisso (o que é na boa), mas....como está a parte da Funcionalidade avançada 3?

Relativamente à minha parte (Funcionalidade avançada 4), penso que hoje ou amanhã já conseguirei acabar....Faltam-me resolver apenas um ou outro problema....

**Comment by Rubenvale31** [comment]
Boas. Eu já começei mas ainda não tive muito tempo para trabalhar. Em principio esta semana na quinta/sexta vou me dedicar e acabar a minha parte.

**Comment by Malhocas** [comment]
Vou pegar hoje na funcionalidade avançada 3, e se tudo correr bem até amanhã ao final do dia deve estar feita. Já agora, quais são os problemas que estás a ter na parte 4?

**Comment by bruno5198** [comment]
Basicamente, se utilizar a imagem do pinguim que o stor tem no guião (apagando-lhe os números, naturalmente), o meu programa reconhece cada um dos olhos do pinguim como tendo 2 contornos (o interno e o externo) e escreve dois números diferentes dentro de cada olho. Só acontece isto para os olhos porque nas restantes regiões, o contorno interno faz parte de uma região e o contorno externo já faz parte de outra região (ou de várias, até).
Neste momento é só este o problema que me falta resolver para ter a funcionalidade avançada 4 pronta...

**Comment by Malhocas** [comment]
Se puseres os olhos pretos, em principio não deves ter esse problema, até porque na figura eles nem têm números,não podes é pintar os olhos depois. Ou então pôr umas pestanas ao pinguim de forma a que o contorno externo toque na região da cabeça.

**Comment by bruno5198** [comment]
Podia fazer isso, mas penso que seria estar a aldrabar a coisa...Supostamente tenho que usar a imagem que me dão, esteja ela como estiver...
