### ISSUE TITLE
Erros conhecidos

### ISSUE THREAD

**Issue by Malhocas** [bruno5198/Trabalho2-Grupo2#8]
Boas malta,
Na última versão que submeti alterei as funções das cores e tamanho, agora quando mudamos a cor ou tamanho, ele não altera a cor da linha toda nem o tamanho, só altera as novas iterações. Tem é o senão de haver um pequeno delay quando se troca de cor ou tamanho, que penso que seja derivado à função de limpar a variável all_coordinates. Este método funciona relativamente bem para a tela branca, mas na câmara sempre que se altera a cor ou tamanho, ele apaga o que já estava desenhado. Ainda estou na dúvida se limpar a variável é o método correto, se tiverem algumas sugestões estejam à vontade para alterar.

Relativamente à função extra 3, ainda experimentei algumas coisas mas estou com alguns problemas a usar a função while com a câmara, e não estou a conseguir guardar os valores do centro quando pressiono a tecla para desenhar (ou seja, o centro e o ponto extremidade ficam com o mesmo valor, e portanto obtenho uma circunferência com raio 0).

**Comment by bruno5198** [comment]
Boas @Malhocas 

Algo que talvez possa ajudar: https://stackoverflow.com/questions/50403176/mouse-events-on-opencv
P.s.: A resposta que tem o certo funciona que já testei...

**Comment by Malhocas** [comment]
Eu entretanto consegui avançar um bocado nesse aspeto, e ele já faz os circulos e retângulos e vê-se eles a crescer, só não dá é para ver a diminuir porque ele está a fazer circulos por cima. Está feito é de uma maneira um bocado grosseira, com código repetido em dois ifs e só está a funcionar para a tela branca. De qualquer maneira vou fazer commit desse código, e amanhã dou uma vista de olhos melhor a essa alternativa e tentar otimizar.

**Comment by Malhocas** [comment]
Esqueci-me de acrescentar, mas ele está a fazer o desenho a clicar nas teclas 's' e 'o', para square e circle, respetivamente, mas só sai do ciclo quando clico na tecla 'p'. Ainda não consegui fazer a funcionar bem só a premir a respetiva letra

**Comment by bruno5198** [comment]
Boas,

@Malhocas
1º - Porquê a tecla 'o' para o círculo? Não faria mais sentido, por exemplo, a tecla 'e' de elipse (que até é a sugestão do professor)
2º - Penso que seria porreiro, para além de quadrados e círculos, o utilizador conseguir desenhar também polígonos, o que achas?
De qualquer forma, envio um código que encontrei na net precisamente para desenhar polígonos (Atenção que não testei este código para ver se realmente funciona, mas parece-me ter tudo para funcionar...): https://stackoverflow.com/questions/37099262/drawing-filled-polygon-using-mouse-events-in-open-cv-using-python/37235130

![Draw_Pilygon](https://user-images.githubusercontent.com/58600049/142613077-97f2d0f2-b7bb-411d-951d-d9b04d7a021a.png)

**Comment by Malhocas** [comment]
Boas,
1º - Fiquei com a ideia que era na tecla 'o', porque o professor inicialmente até referia essa tecla, é uma questão de mudar a condição do if
2º - Quanto ao desenho de poligonos, é uma opção interessante mas secalhar só focava nela quando a funcionalidade 3 estivesse a funcionar melhor, e outros aspetos do programa também. De qualquer maneira, a minha abordagem para o desenho de poligonos seria o uso de uma tecla nova para começar a desenhar o poligono, outra tecla para guardar posições do centroide, e possivelmente a tecla para sair da opção poligono já faria o poligono, que achas? Se conseguir fazer no circulo e no quadrado só com o premir da tecla, ainda serão precisos menos teclas para o poligono (2 em principio)

**Comment by bruno5198** [comment]
1º - De qualquer forma....o código que tens/que estás a fazer faz círculos ou elipses? É que também não faz muito sentido estar a usar a tecla 'e' de elipse e depois poder desenhar apenas círculos...
2º - Sim, isto do desenho de polígonos já seria um extra, primeiro tudo o resto tem que estar a funcionar bem. Eu sinceramente optava por puma abordagem um pouco diferente....Acho que faria sentido existir uma tecla ('p', por exemplo) que quando é premida pela primeira vez inicia o desenho de polígonos (que depois seria feito com as teclas do rato do lado direito (para definir pontos) e esquerdo (para concluir um dado polígono)) e, quando essa mesma tecla ('p') fosse premida uma segunda vez, parava o desenho de polígonos.... Mas, faz como achares melhor....

O resto da malta (@Rubenvale31 @PedroRibeiro37 ) que dê a sua opinião, também...

**Comment by Malhocas** [comment]
Boas,
AInda não consegui fazer os circulos/quadrados a manter a tecla premida, mas já consegui fazer com que ele comece a fazer o circulo clicando na tecla 'o', e só sai desse menu voltando a clicar na tecla 'o', o mesmo para os quadrados. Também já consegui implementar a função de fazer poligonos, usando a tecla 'p' para começar o processo, e novamente a tecla 'p' para ir adicionando pontos, e finalmente a tecla 'x' para sair e ele apresentar o poligono na tela branca. Ao contrario do circulo e quadrado, no poligono não estou a conseguir fazer preview de como vai ficar o poligono, porque apesar de estar dentro do ciclo while, cada ponto está associado a um novo if, e a imagem da camara mete logo o novo frame por cima. Já dei commit

**Comment by bruno5198** [comment]
Boas
@Malhocas
Aquele link que tinha enviado não ajudou nessa parte do preview?
E.....Não seria melhor usar as teclas do rato para o polígono? A tecla da esquerda para adicionar pontos e a da direita para "acabar" o polígono...

**Comment by PedroRibeiro37** [comment]
Até podiamos usar o butão do rato da direita para acabar todas as figuras... asssim até ficava mais 'user friendly'

**Comment by Malhocas** [comment]
Optei por fazer assim porque nos outros dois, a pedido do prof, é a usar as teclas, portanto quis fugir um bocado ao rato para ficar similar.
Quanto ao preview vou experimentar com um novo array, penso que seja isso
